spring.application.name=parcialdos
server.port=8080
#datos para conectarse a la base de datos en mysql:
spring.datasource.url=jdbc:mysql://localhost:3306/bankdb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123j
spring.jpa.hibernate.ddl-auto=none

Spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

